services:
  postgres:
    image: postgres:15-alpine
    container_name: hw-db-postgres
    environment:
      POSTGRES_DB: hw-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: wasd123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hw-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d hw-db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  hw-network:
    driver: bridge
